// <auto-generated />
using System;
using AuthBackend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthBackend.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260325000000_AddAttendanceDailyUniqueConstraint")]
    partial class AddAttendanceDailyUniqueConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AuthBackend.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<int>("ActionType").HasColumnType("INTEGER");
                    b.Property<DateTime>("Timestamp").HasColumnType("TEXT");
                    b.Property<Guid>("UserId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "ActionType");
                    b.ToTable("AttendanceRecords", (string)null);
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.EstadoUsuario", b =>
                {
                    b.Property<int>("Id").HasColumnType("INTEGER");
                    b.Property<string>("Descripcion").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Nombre").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("EstadosUsuario", (string)null);
                    b.HasData(
                        new { Id = 1, Descripcion = "Usuario activo con acceso completo", Nombre = "Activo" },
                        new { Id = 2, Descripcion = "Usuario inactivo sin acceso", Nombre = "Inactivo" },
                        new { Id = 3, Descripcion = "Usuario suspendido temporalmente", Nombre = "Suspendido" });
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.Sesion", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("FechaCreacion").HasColumnType("TEXT");
                    b.Property<DateTime>("FechaExpiracion").HasColumnType("TEXT");
                    b.Property<DateTime?>("FechaRevocacion").HasColumnType("TEXT");
                    b.Property<string>("RefreshToken").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<bool>("Revocado").HasColumnType("INTEGER");
                    b.Property<Guid>("UsuarioId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RefreshToken").IsUnique();
                    b.HasIndex("UsuarioId");
                    b.ToTable("Sesiones", (string)null);
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.TokenRecuperacion", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("FechaCreacion").HasColumnType("TEXT");
                    b.Property<DateTime>("FechaExpiracion").HasColumnType("TEXT");
                    b.Property<DateTime?>("FechaUso").HasColumnType("TEXT");
                    b.Property<string>("Token").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<bool>("Usado").HasColumnType("INTEGER");
                    b.Property<Guid>("UsuarioId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Token").IsUnique();
                    b.HasIndex("UsuarioId");
                    b.ToTable("TokensRecuperacion", (string)null);
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.UserPresence", b =>
                {
                    b.Property<Guid>("UserId").HasColumnType("TEXT");
                    b.Property<DateTime>("LastSeenUtc").HasColumnType("TEXT");
                    b.HasKey("UserId");
                    b.ToTable("UserPresence", (string)null);
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Apellidos").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("Cedula").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<int>("EstadoId").ValueGeneratedOnAdd().HasColumnType("INTEGER").HasDefaultValue(1);
                    b.Property<DateTime?>("FechaActualizacion").HasColumnType("TEXT");
                    b.Property<DateTime>("FechaCreacion").HasColumnType("TEXT");
                    b.Property<string>("Nombres").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Cedula").IsUnique();
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("EstadoId");
                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("AuthBackend.Domain.Entities.Usuario", "Usuario")
                        .WithMany().HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.UserPresence", b =>
                {
                    b.HasOne("AuthBackend.Domain.Entities.Usuario", "Usuario")
                        .WithMany().HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuthBackend.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AuthBackend.Domain.Entities.EstadoUsuario", "Estado")
                        .WithMany().HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
